### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by dariathehuman** [mates4352/PetCare#20]
Подключены правильно, в этом плане все окей. 
Однако для веба лучше всего использовать форматы woff2 и woff (подключать надо оба обязательно), причем woff2 должен идти первым, как более современный. 

Проверила миксины, там даже указан woff2 и woff, а в папке лежит ttf. Как так получилось?

**Comment by mates4352** [comment]
Шрифты  для самого проекта лежит в папке dist в 2 форматах

**Comment by dariathehuman** [comment]
Ага, нашла преобразование в gulp. Гуд, закрываем тогда этот вопрос
